'use strict';
/* All beginner-facing content lives here so it is easy to edit. */
window.EE_DATA = (function () {
  /* ---------- "What do you want to do?" ---------- */
  const TASKS = [
    { q: 'Add up a column of numbers', kw: 'add sum total plus column row numbers adding up', formula: '=SUM(B2:B6)', steps: ['Click the empty cell where you want the answer.', 'Type =SUM( then drag your mouse over the numbers you want added.', 'Type ) and press Enter.'], tip: 'Shortcut: click the cell under your numbers and press Alt + = (Windows) or Cmd + Shift + T (Mac). Excel writes SUM for you.' },
    { q: 'Find the average', kw: 'average mean typical', formula: '=AVERAGE(B2:B6)', steps: ['Click the cell for the answer.', 'Type =AVERAGE( and select your numbers.', 'Type ) and press Enter.'] },
    { q: 'Find the biggest or smallest number', kw: 'biggest largest highest max maximum smallest lowest min minimum', formula: '=MAX(B2:B6)', steps: ['For the biggest, type =MAX( and select your numbers. For the smallest, use =MIN( instead.', 'Close with ) and press Enter.'] },
    { q: 'Count how many items I have', kw: 'count how many number of items entries rows', formula: '=COUNTA(A2:A6)', steps: ['=COUNTA counts every cell that is not empty (good for names).', '=COUNT only counts cells that contain numbers.'] },
    { q: 'Multiply two columns (e.g. price × quantity)', kw: 'multiply times price quantity qty cost line total', formula: '=B2*C2', steps: ['In the first row, type = then click the price cell.', 'Type * (the star means "times") then click the quantity cell.', 'Press Enter, then copy the formula down (see "Copy a formula down").'] },
    { q: 'Copy a formula down the whole column', kw: 'copy fill down drag autofill formula column same', formula: '', steps: ['Click the cell that has the formula you like.', 'Move your mouse to the small green square at its bottom-right corner. The pointer becomes a thin black +.', 'Double-click the square (Excel fills down as far as your data goes) or drag it down.'], tip: 'Excel automatically adjusts the cell names for each row. That is what makes this so powerful.' },
    { q: 'Work out a percentage', kw: 'percent percentage % share proportion', formula: '=B2/B8', steps: ['Divide the part by the whole: =part/whole.', 'Click the % button on the Home tab to show it as a percentage (0.25 becomes 25%).'] },
    { q: 'Add or take off a percentage (e.g. tax, discount)', kw: 'tax vat discount markup increase decrease percent off sale', formula: '=B2*(1-10%)', steps: ['To take 10% off: =price*(1-10%).', 'To add 10% on top: =price*(1+10%).'] },
    { q: 'Round a number', kw: 'round decimal places whole number nearest', formula: '=ROUND(B2,0)', steps: ['=ROUND(number, places). Use 0 places for a whole number, 2 for cents/pence.'] },
    { q: 'Show one thing if true, another if not', kw: 'if condition decide pass fail yes no check test', formula: '=IF(B2>=50,"Pass","Fail")', steps: ['=IF(test, answer if true, answer if not).', 'Text answers go in "double quotes"; numbers do not.'] },
    { q: 'Add up only some rows (e.g. just one category)', kw: 'sumif conditional only category where matching total by', formula: '=SUMIF(A2:A6,"Apples",D2:D6)', steps: ['=SUMIF(cells to check, what to look for, cells to add up).', 'The two groups of cells must be the same size.'] },
    { q: 'Count only some rows', kw: 'countif conditional how many match greater than', formula: '=COUNTIF(B2:B6,">2")', steps: ['=COUNTIF(cells to check, rule).', 'Rules with symbols go in quotes: ">5", "<=10", "<>0".'] },
    { q: 'Look up a value from a table', kw: 'lookup vlookup find match price for code name table', formula: '=VLOOKUP("Milk",A2:D6,2,FALSE)', steps: ['=VLOOKUP(what to find, table, column number, FALSE).', 'The thing you are finding must be in the FIRST column of the table.', 'Always end with FALSE so you get an exact match.'], tip: 'Newer Excel also has XLOOKUP, which is friendlier — but VLOOKUP works everywhere.' },
    { q: 'Join first name and last name together', kw: 'join combine concatenate merge names text together full name', formula: '=A2&" "&B2', steps: ['The & symbol glues text together.', 'The " " in the middle adds a space between the names.'] },
    { q: 'Make text CAPITALS, lowercase or Title Case', kw: 'upper lower proper capital uppercase lowercase title case text', formula: '=PROPER(A2)', steps: ['=UPPER(A2) makes CAPITALS, =LOWER(A2) makes lowercase, =PROPER(A2) makes Title Case.'] },
    { q: 'Remove extra spaces from text', kw: 'trim spaces clean extra space tidy', formula: '=TRIM(A2)', steps: ['=TRIM(A2) removes extra spaces at the start, end and between words.'] },
    { q: "Put in today's date", kw: 'today date current now', formula: '=TODAY()', steps: ['Type =TODAY() and press Enter. It updates every day.', 'Want a date that never changes? Press Ctrl + ; (semicolon).'] },
    { q: 'Sort my data A to Z or smallest to largest', kw: 'sort order alphabetical ascending descending rank', formula: '', steps: ['Click any cell inside your data.', 'Go to the Data tab and click the A→Z button (smallest first) or Z→A (largest first).', 'To sort by a different column, click a cell in that column first.'], tip: 'Make sure every column has a heading in the top row so Excel does not sort the headings too.' },
    { q: 'Show only some rows (filter)', kw: 'filter hide show only search narrow down', formula: '', steps: ['Click any cell in your data.', 'Press Ctrl + Shift + L (or Data tab → Filter).', 'Click the little arrow on a heading and tick the items you want to see.', 'To bring everything back, press Ctrl + Shift + L again.'], tip: 'Filtering never deletes anything. Hidden rows are still there.' },
    { q: 'Make a chart', kw: 'chart graph plot bar pie line visual', formula: '', steps: ['Select your data, including the headings.', 'Go to the Insert tab → Recommended Charts.', 'Click a chart you like and press OK.', 'Click the chart title to rename it.'] },
    { q: 'Make my numbers look like money', kw: 'currency money dollar pound euro format decimal', formula: '', steps: ['Select the cells.', 'On the Home tab, click the $ button (or use the dropdown that says "General" and choose Currency).', 'Use the .0 → .00 buttons to show more or fewer decimals.'] },
    { q: 'Make the headings stand out', kw: 'bold heading header colour color style format fill', formula: '', steps: ['Select the heading row.', 'Press Ctrl + B for bold.', 'Use the paint bucket on the Home tab to give it a colour.'] },
    { q: 'Make columns wide enough to read', kw: 'column width wide narrow cut off hashes #### autofit resize', formula: '', steps: ['Move your mouse to the line between two column letters at the top.', 'Double-click. Excel fits the column to its contents.', 'Seeing #### in a cell? The column is just too narrow. This fixes it.'] },
    { q: 'Freeze the top row so headings stay visible', kw: 'freeze pane header scroll stay top row', formula: '', steps: ['Go to the View tab.', 'Click Freeze Panes → Freeze Top Row.'] },
    { q: 'Remove duplicates', kw: 'duplicate duplicates remove repeated same unique', formula: '', steps: ['Click inside your data.', 'Data tab → Remove Duplicates.', 'Choose which columns to compare and press OK.'], tip: 'Try it on a copy first, since this deletes rows.' },
    { q: 'Undo a mistake', kw: 'undo mistake oops wrong go back redo', formula: '', steps: ['Press Ctrl + Z (Cmd + Z on Mac). Press it again to keep going back.', 'Press Ctrl + Y to redo.'], tip: 'Nothing you do in Excel is scary as long as Ctrl + Z works.' },
    { q: 'Save my work', kw: 'save file keep store', formula: '', steps: ['Press Ctrl + S (Cmd + S on Mac).', 'The first time, choose where to save it and give it a name.', 'After that, Ctrl + S just updates the file. Do it often!'] },
    { q: 'Print or make a PDF', kw: 'print pdf export paper page', formula: '', steps: ['Press Ctrl + P.', 'Check the preview on the right.', 'To make a PDF, choose "Microsoft Print to PDF" (or Save as PDF) as the printer.'], tip: 'If the page is cut off, set Scaling to "Fit All Columns on One Page".' },
    { q: 'Hide an ugly error like #DIV/0!', kw: 'error hide iferror blank replace ugly', formula: '=IFERROR(B2/C2,"")', steps: ['Wrap your formula in IFERROR: =IFERROR(your formula, what to show instead).', '"" (two quotes) means "show nothing".'] },
    { q: 'Keep one cell fixed when copying a formula', kw: 'absolute dollar fixed lock reference $ anchor stay', formula: '=B2*$F$1', steps: ['Click in the formula and press F4. Excel adds $ signs: $F$1.', '$ means "do not move this when copying".', 'Use it for things like a tax rate that lives in a single cell.'] },
  ];

  /* ---------- Formula builder ---------- */
  const BUILDER = [
    { id: 'SUM', name: 'Add numbers (SUM)', blurb: 'Adds up a group of numbers.', fields: [{ k: 'r', label: 'Which cells do you want to add up?', hint: 'Type the first and last cell with a colon between, like B2:B6.', def: 'B2:B6' }], make: (v) => `=SUM(${v.r})` },
    { id: 'AVERAGE', name: 'Find the average', blurb: 'The typical value: total divided by how many.', fields: [{ k: 'r', label: 'Which cells?', hint: 'Like B2:B6.', def: 'B2:B6' }], make: (v) => `=AVERAGE(${v.r})` },
    { id: 'MAXMIN', name: 'Biggest or smallest', blurb: 'Finds the highest or lowest number.', fields: [{ k: 'w', label: 'Which do you want?', type: 'select', options: [['MAX', 'The biggest number'], ['MIN', 'The smallest number']], def: 'MAX' }, { k: 'r', label: 'Which cells?', hint: 'Like B2:B6.', def: 'B2:B6' }], make: (v) => `=${v.w}(${v.r})` },
    { id: 'COUNT', name: 'Count items', blurb: 'Counts how many cells have something in them.', fields: [{ k: 'w', label: 'What should be counted?', type: 'select', options: [['COUNTA', 'Anything (names, numbers, dates)'], ['COUNT', 'Only numbers']], def: 'COUNTA' }, { k: 'r', label: 'Which cells?', hint: 'Like A2:A20.', def: 'A2:A6' }], make: (v) => `=${v.w}(${v.r})` },
    { id: 'MULT', name: 'Multiply two cells', blurb: 'For things like price × quantity.', fields: [{ k: 'a', label: 'First cell', hint: 'Like B2.', def: 'B2' }, { k: 'b', label: 'Second cell', hint: 'Like C2.', def: 'C2' }], make: (v) => `=${v.a}*${v.b}` },
    { id: 'PERCENT', name: 'What percent is it?', blurb: 'Turns "part of a whole" into a percentage.', fields: [{ k: 'a', label: 'The part', hint: 'Cell with the smaller number.', def: 'B2' }, { k: 'b', label: 'The whole', hint: 'Cell with the total.', def: 'B8' }], make: (v) => `=${v.a}/${v.b}`, after: 'Then click the % button on the Home tab so it shows as a percentage.' },
    { id: 'DISCOUNT', name: 'Add or remove a percentage', blurb: 'Discounts, tax, price rises.', fields: [{ k: 'w', label: 'What do you want to do?', type: 'select', options: [['-', 'Take a percentage off'], ['+', 'Add a percentage on']], def: '-' }, { k: 'a', label: 'Cell with the price', hint: 'Like B2.', def: 'B2' }, { k: 'p', label: 'The percentage', hint: 'Just the number, like 10 for 10%.', def: '10' }], make: (v) => `=${v.a}*(1${v.w}${v.p || 0}%)` },
    { id: 'ROUND', name: 'Round a number', blurb: 'Tidy up long decimals.', fields: [{ k: 'a', label: 'Cell to round', hint: 'Like B2.', def: 'B2' }, { k: 'd', label: 'How many decimal places?', hint: '0 = whole number, 2 = like money.', def: '2' }], make: (v) => `=ROUND(${v.a},${v.d || 0})` },
    { id: 'IF', name: 'If this, then that', blurb: 'Show one answer or another depending on a test.', fields: [{ k: 'a', label: 'Which cell do you want to test?', hint: 'Like B2.', def: 'B2' }, { k: 'op', label: 'The test', type: 'select', options: [['>=', 'is at least (≥)'], ['>', 'is more than (>)'], ['<=', 'is at most (≤)'], ['<', 'is less than (<)'], ['=', 'is exactly equal to'], ['<>', 'is not equal to']], def: '>=' }, { k: 'n', label: 'Compare with', hint: 'A number or a cell.', def: '50' }, { k: 'yes', label: 'If the test is true, show', hint: 'Words are fine, e.g. Pass.', def: 'Pass' }, { k: 'no', label: 'If not, show', hint: 'Words are fine, e.g. Fail.', def: 'Fail' }], make: (v) => `=IF(${v.a}${v.op}${v.n},${q(v.yes)},${q(v.no)})` },
    { id: 'SUMIF', name: 'Add up only matching rows', blurb: 'Like SUM, but only for rows that match.', fields: [{ k: 'c', label: 'Cells to check', hint: 'The column with the categories, like A2:A20.', def: 'A2:A6' }, { k: 'm', label: 'What should they match?', hint: 'A word such as Apples.', def: 'Apples' }, { k: 's', label: 'Cells to add up', hint: 'Same size as the first group, like D2:D20.', def: 'D2:D6' }], make: (v) => `=SUMIF(${v.c},${q(v.m)},${v.s})` },
    { id: 'COUNTIF', name: 'Count only matching rows', blurb: 'How many rows match a rule?', fields: [{ k: 'c', label: 'Cells to check', hint: 'Like A2:A20.', def: 'B2:B6' }, { k: 'm', label: 'Rule', hint: 'A word (Apples) or a test (>5, <=10, <>0).', def: '>2' }], make: (v) => `=COUNTIF(${v.c},${q(v.m)})` },
    { id: 'VLOOKUP', name: 'Look something up in a table', blurb: 'Finds a row by name/code and returns another column.', fields: [{ k: 'f', label: 'What are you looking for?', hint: 'A cell (like F2) or a word.', def: 'Milk' }, { k: 't', label: 'Where is the table?', hint: 'The whole table, like A2:D20. What you look up must be in its first column.', def: 'A2:D6' }, { k: 'c', label: 'Which column do you want back?', hint: 'Count from the left of the table: 1, 2, 3…', def: '2' }], make: (v) => `=VLOOKUP(${/^[A-Za-z]{1,3}\d+$/.test(v.f) ? v.f : q(v.f)},${v.t},${v.c},FALSE)` },
    { id: 'JOIN', name: 'Join text together', blurb: 'Like first name + last name.', fields: [{ k: 'a', label: 'First cell', hint: 'Like A2.', def: 'A2' }, { k: 'sep', label: 'What goes in between?', hint: 'A space is most common. Leave blank for nothing.', def: ' ' }, { k: 'b', label: 'Second cell', hint: 'Like B2.', def: 'B2' }], make: (v) => `=${v.a}&${q(v.sep || '')}&${v.b}` },
    { id: 'SAFE', name: 'Hide errors', blurb: 'Replace an error with something tidy.', fields: [{ k: 'f', label: 'Your formula (without the =)', hint: 'Like B2/C2.', def: 'B2/C2' }, { k: 'o', label: 'Show this instead of an error', hint: 'Leave blank to show nothing.', def: '' }], make: (v) => `=IFERROR(${v.f.replace(/^=/, '')},${q(v.o || '')})` },
  ];
  function q(s) { s = String(s == null ? '' : s); return /^-?\d+(\.\d+)?$/.test(s.trim()) && s.trim() !== '' ? s.trim() : '"' + s.replace(/"/g, '""') + '"'; }

  /* ---------- Lessons ---------- */
  const LESSONS = [
    { id: 'screen', title: 'Meet the Excel screen', mins: 3, intro: 'Excel looks busy, but you only need to know six things.', steps: ['<b>Cell</b> – one box. Click it to select it. Its name (like <b>B3</b>) is its column letter + row number.', '<b>Columns</b> run up and down and have letters (A, B, C…). <b>Rows</b> run across and have numbers (1, 2, 3…).', '<b>The ribbon</b> is the strip of buttons at the top. Its tabs (Home, Insert, Data…) group the buttons.', '<b>The formula bar</b> sits above the grid. It shows exactly what is inside the selected cell.', '<b>Sheet tabs</b> at the bottom let you have several pages in one file. Click <b>+</b> to add one.', '<b>The Name Box</b> (top left) shows which cell you are in. Type a cell name there and press Enter to jump to it.'], practice: null },
    { id: 'type', title: 'Typing and moving around', mins: 3, intro: 'The basics: putting things into cells.', steps: ['Click a cell and just start typing. No need to double-click.', 'Press <b>Enter</b> to finish and move down. Press <b>Tab</b> to finish and move right.', 'Press <b>Esc</b> to cancel what you are typing.', 'To change a cell, click it and start typing (this replaces it), or press <b>F2</b> to edit what is already there.', 'To delete, select cells and press <b>Delete</b>.', 'Made a mistake? Press <b>Ctrl + Z</b> (Cmd + Z on Mac). You can undo many steps.'], practice: 'Try it in the practice sheet: click a cell, type your name and press Enter.' },
    { id: 'first', title: 'Your first formula', mins: 4, intro: 'A formula is a cell that does maths for you. It always starts with <b>=</b>.', steps: ['Click an empty cell and type <b>=2+3</b>, then press Enter. You will see <b>5</b>.', 'Click that cell again and look at the formula bar: it still says =2+3. The cell shows the answer; the bar shows the recipe.', '<b>+</b> add, <b>−</b> subtract, <b>*</b> multiply, <b>/</b> divide.', 'Better: use cell names. Type 10 in A1 and 5 in A2. In A3 type <b>=A1+A2</b>.', 'Change A1 to 20. A3 updates by itself. That is the magic of Excel.'], practice: 'Try =A1+A2 in the practice sheet.', example: '=B2*C2' },
    { id: 'sum', title: 'Adding up with SUM', mins: 3, intro: 'Adding lots of numbers with + is slow. SUM does it in one go.', steps: ['Click the cell where you want the total.', 'Type <b>=SUM(</b>.', 'Drag your mouse over the numbers. Excel writes the range for you, like <b>B2:B6</b> (the colon means "through").', 'Type <b>)</b> and press Enter.', 'Even faster: click below the numbers and press <b>Alt + =</b>. Excel guesses the range.'], practice: 'Try =SUM(D2:D6) in the practice sheet.', example: '=SUM(D2:D6)' },
    { id: 'avg', title: 'Average, biggest, smallest, count', mins: 3, intro: 'Four more one-word helpers, all used exactly like SUM.', steps: ['<b>=AVERAGE(B2:B6)</b> – the typical number.', '<b>=MAX(B2:B6)</b> – the biggest.', '<b>=MIN(B2:B6)</b> – the smallest.', '<b>=COUNT(B2:B6)</b> – how many numbers.', 'All follow the same pattern: <b>=NAME( cells )</b>.'], practice: 'Try each one on the prices in column B.', example: '=AVERAGE(B2:B6)' },
    { id: 'look', title: 'Make it look nice', mins: 4, intro: 'Good looks make a sheet easy to read.', steps: ['Select the heading row, press <b>Ctrl + B</b> for bold.', 'Double-click the line between two column letters to fit the column to its contents.', 'Select money cells and click the <b>$</b> button on the Home tab.', 'Use the <b>paint bucket</b> to colour cells and the <b>A</b> button to colour text.', 'Use <b>borders</b> (the square icon) to draw lines around a table.', 'Seeing <b>####</b>? The column is too narrow. Widen it.'], practice: null },
    { id: 'sort', title: 'Sort and filter', mins: 3, intro: 'Put things in order, or hide what you do not need.', steps: ['Click any cell in your table.', '<b>Sort:</b> Data tab → A→Z (smallest first) or Z→A.', '<b>Filter:</b> press <b>Ctrl + Shift + L</b>. Arrows appear on your headings.', 'Click an arrow, tick what to show, press OK.', 'Press Ctrl + Shift + L again to turn filtering off.', 'Filtering only <i>hides</i> rows. It never deletes them.'], practice: null },
    { id: 'copy', title: 'Copy a formula down', mins: 4, intro: 'Write a formula once, then reuse it on every row.', steps: ['Write the formula in the first row, e.g. <b>=B2*C2</b>.', 'Click it. Find the small green square in its bottom-right corner (the <b>fill handle</b>).', 'Double-click the square. Excel copies the formula down as far as your data goes.', 'Look at the copies: row 3 says =B3*C3, row 4 says =B4*C4. Excel changed the row numbers for you.', 'Need a cell to stay put (like a tax rate in F1)? Write <b>$F$1</b>. The $ signs lock it. Press <b>F4</b> to add them quickly.'], practice: 'In the practice sheet, type =B2*C2 in D2, then fix it by hand in D3…', example: '=B2*C2' },
    { id: 'if', title: 'Letting Excel decide with IF', mins: 4, intro: 'IF shows one thing when a test is true and another when it is not.', steps: ['The pattern: <b>=IF( test , if true , if false )</b>.', 'Example: <b>=IF(B2>=2,"Pricey","Cheap")</b>.', 'Words go in <b>"double quotes"</b>. Numbers do not.', 'Tests use <b>&gt;</b> more than, <b>&lt;</b> less than, <b>=</b> equal, <b>&lt;&gt;</b> not equal, <b>&gt;=</b> at least.', 'Use the Formula Builder tab and pick "If this, then that" to fill it in without typing.'], practice: 'Try the example in the practice sheet.', example: '=IF(B2>=2,"Pricey","Cheap")' },
    { id: 'chart', title: 'Make a chart in 3 clicks', mins: 3, intro: 'Charts turn numbers into pictures.', steps: ['Select your data including the headings.', 'Click <b>Insert → Recommended Charts</b>.', 'Pick one that looks good and press OK.', 'Click the chart title to rename it.', 'Bar charts compare things, line charts show change over time, pie charts show parts of a whole.'], practice: null },
    { id: 'save', title: 'Save, print and share', mins: 3, intro: 'Do not lose your work!', steps: ['<b>Ctrl + S</b> saves (Cmd + S on Mac). Do it every few minutes.', 'The first time, choose a place and name.', 'To print, press <b>Ctrl + P</b> and check the preview.', 'To make a PDF, pick <b>Save as PDF</b> / <b>Print to PDF</b> as the printer.', 'To email it, File → Share (or attach the saved file).', 'If Excel crashes, reopen it: it usually offers to recover your work.'], practice: null },
  ];

  /* ---------- Errors ---------- */
  const ERRORS = [
    { code: '####', what: 'The column is too narrow to show the answer.', fix: 'Double-click the line on the right edge of the column letter to widen it. Nothing is wrong with your data.' },
    { code: '#DIV/0!', what: 'Something was divided by zero or by an empty cell.', fix: 'Look at the number or cell after the "/". Make sure it is not 0 or empty. Or wrap the formula: =IFERROR(B2/C2,"").' },
    { code: '#NAME?', what: "Excel doesn't recognise a word in your formula.", fix: 'Usually a typo in a function name (SUMM instead of SUM), or text missing its "double quotes".' },
    { code: '#VALUE!', what: 'The formula is trying to do maths with something that is not a number (often text or a stray space).', fix: 'Check the cells used in the formula. Look for words, or numbers with spaces. Use TRIM() to remove spaces.' },
    { code: '#REF!', what: 'The formula points at a cell that was deleted or does not exist.', fix: 'Press Ctrl + Z to undo the delete, or retype the formula with the right cells.' },
    { code: '#N/A', what: 'A lookup (like VLOOKUP) could not find what you asked for.', fix: 'Check spelling and extra spaces. Make sure what you are looking for is in the first column of the table, and end with ,FALSE.' },
    { code: '#NUM!', what: 'A number is too big, too small, or invalid for the calculation.', fix: 'Check the numbers used. For example, you cannot take the square root of a negative number.' },
    { code: '#NULL!', what: 'A space was used where a colon or comma belongs.', fix: 'Use a colon for a range (A1:A5) and commas between separate items (A1,A5).' },
    { code: 'Circular reference', what: 'A formula refers to its own cell, directly or through others, so it can never finish.', fix: 'Excel shows a warning. Click the formula and make sure the range does not include the cell holding the formula itself.' },
    { code: 'Formula shows as text', what: 'You see =SUM(A1:A3) instead of the answer.', fix: 'The cell is formatted as Text, or there is a space/apostrophe before the =. Change the format to General, then click the cell and press Enter.' },
    { code: 'Numbers will not add up', what: 'SUM gives 0 or the wrong total, and the numbers are left-aligned.', fix: 'They are stored as text. Select them, click the yellow warning icon and choose "Convert to Number".' },
  ];

  /* ---------- Glossary ---------- */
  const GLOSSARY = [
    ['Workbook', 'An Excel file. It can hold many sheets.'],
    ['Worksheet / sheet', 'One page (grid) inside a workbook. Tabs at the bottom switch between them.'],
    ['Cell', 'One box in the grid. Its name is the column letter then the row number, like B3.'],
    ['Column', 'A vertical line of cells, labelled with letters.'],
    ['Row', 'A horizontal line of cells, labelled with numbers.'],
    ['Range', 'A group of cells. B2:B6 means "B2 through B6".'],
    ['Formula', 'A cell that calculates something. Always starts with =.'],
    ['Function', 'A ready-made calculation with a name, like SUM or AVERAGE. You give it cells in brackets.'],
    ['Cell reference', 'A cell name (like A1) used inside a formula.'],
    ['Absolute reference', 'A reference with $ signs ($A$1) that does not move when you copy the formula.'],
    ['Formula bar', 'The bar above the grid that shows what is in the selected cell.'],
    ['Name Box', 'The small box at top left that shows the selected cell. Type a cell name to jump there.'],
    ['Ribbon', 'The strip of tabs and buttons across the top.'],
    ['Fill handle', 'The small green square at the bottom-right of a selected cell. Drag or double-click to copy down.'],
    ['Filter', 'Hides rows that do not match what you choose. Nothing is deleted.'],
    ['Sort', 'Puts rows in order (A→Z, smallest→largest).'],
    ['Table', 'A block of data with headings. Excel can turn it into a fancy Table (Ctrl + T) with built-in filters.'],
    ['Pivot table', 'A tool that summarises lots of data into a small report. A later-stage skill.'],
    ['Chart', 'A picture made from your numbers.'],
    ['Freeze panes', 'Keeps headings visible while you scroll.'],
    ['Argument', 'One of the things you put inside a function’s brackets. In =SUM(A1,B1) the arguments are A1 and B1.'],
    ['Operator', 'A symbol such as + − * / that tells Excel what to do with two values.'],
  ];

  /* ---------- Shortcuts ---------- */
  const SHORTCUTS = [
    ['Ctrl + Z', 'Undo (your safety net)'], ['Ctrl + Y', 'Redo'], ['Ctrl + S', 'Save'], ['Ctrl + C / X / V', 'Copy / Cut / Paste'],
    ['Ctrl + B', 'Bold'], ['Ctrl + A', 'Select everything'], ['Ctrl + F', 'Find'], ['Ctrl + P', 'Print'],
    ['Ctrl + Arrow key', 'Jump to the edge of your data'], ['Ctrl + Home', 'Jump to cell A1'], ['F2', 'Edit the selected cell'], ['F4', 'Add $ signs to a cell reference'],
    ['Alt + =', 'Insert a SUM'], ['Ctrl + Shift + L', 'Turn filters on/off'], ['Ctrl + ;', "Insert today's date"], ['Ctrl + Space', 'Select the whole column'], ['Shift + Space', 'Select the whole row'], ['Enter / Tab', 'Finish typing and move down / right'],
  ];

  /* ---------- Practice sheet starter ---------- */
  const SAMPLE = { A1: 'Item', B1: 'Price', C1: 'Qty', D1: 'Total', A2: 'Apples', B2: '1.5', C2: '4', D2: '=B2*C2', A3: 'Bread', B3: '2.25', C3: '2', D3: '=B3*C3', A4: 'Milk', B4: '1.2', C4: '3', D4: '=B4*C4', A5: 'Eggs', B5: '3.4', C5: '1', D5: '=B5*C5', A6: 'Coffee', B6: '7.9', C6: '2', D6: '=B6*C6', A8: 'Grand total', D8: '=SUM(D2:D6)' };

  const CHALLENGES = [
    { text: 'Type your name into cell F1.', check: (s) => /\S/.test(s.getRaw('F1')) },
    { text: 'In D7, add up the Qty column (C2:C6) with SUM.', check: (s) => /^=\s*SUM\(/i.test(s.getRaw('D7')) && s.value('D7') === 12 },
    { text: 'In E2, show "Pricey" if the price in B2 is 2 or more, otherwise "Cheap", using IF.', check: (s) => /^=\s*IF\(/i.test(s.getRaw('E2')) && /pricey|cheap/i.test(s.getRaw('E2')) },
    { text: 'In E8, find the average price with AVERAGE(B2:B6).', check: (s) => { try { return Math.abs(Number(s.value('E8')) - 3.25) < 1e-9; } catch (e) { return false; } } },
  ];

  return { TASKS, BUILDER, LESSONS, ERRORS, GLOSSARY, SHORTCUTS, SAMPLE, CHALLENGES };
})();
