'use strict';
/* Premium content: only ever sent to signed-in subscribers by server.js */
window.EE_PREMIUM = (function () {
  /* ---------- Formula builder ---------- */
  const BUILDER = [
    { id: 'SUM', name: 'Add numbers (SUM)', blurb: 'Adds up a group of numbers.', fields: [{ k: 'r', label: 'Which cells do you want to add up?', hint: 'Type the first and last cell with a colon between, like B2:B6.', def: 'B2:B6' }], make: (v) => `=SUM(${v.r})` },
    { id: 'AVERAGE', name: 'Find the average', blurb: 'The typical value: total divided by how many.', fields: [{ k: 'r', label: 'Which cells?', hint: 'Like B2:B6.', def: 'B2:B6' }], make: (v) => `=AVERAGE(${v.r})` },
    { id: 'MAXMIN', name: 'Biggest or smallest', blurb: 'Finds the highest or lowest number.', fields: [{ k: 'w', label: 'Which do you want?', type: 'select', options: [['MAX', 'The biggest number'], ['MIN', 'The smallest number']], def: 'MAX' }, { k: 'r', label: 'Which cells?', hint: 'Like B2:B6.', def: 'B2:B6' }], make: (v) => `=${v.w}(${v.r})` },
    { id: 'COUNT', name: 'Count items', blurb: 'Counts how many cells have something in them.', fields: [{ k: 'w', label: 'What should be counted?', type: 'select', options: [['COUNTA', 'Anything (names, numbers, dates)'], ['COUNT', 'Only numbers']], def: 'COUNTA' }, { k: 'r', label: 'Which cells?', hint: 'Like A2:A20.', def: 'A2:A6' }], make: (v) => `=${v.w}(${v.r})` },
    { id: 'MULT', name: 'Multiply two cells', blurb: 'For things like price × quantity.', fields: [{ k: 'a', label: 'First cell', hint: 'Like B2.', def: 'B2' }, { k: 'b', label: 'Second cell', hint: 'Like C2.', def: 'C2' }], make: (v) => `=${v.a}*${v.b}` },
    { id: 'PERCENT', name: 'What percent is it?', blurb: 'Turns "part of a whole" into a percentage.', fields: [{ k: 'a', label: 'The part', hint: 'Cell with the smaller number.', def: 'B2' }, { k: 'b', label: 'The whole', hint: 'Cell with the total.', def: 'B8' }], make: (v) => `=${v.a}/${v.b}`, after: 'Then click the % button on the Home tab so it shows as a percentage.' },
    { id: 'DISCOUNT', name: 'Add or remove a percentage', blurb: 'Discounts, tax, price rises.', fields: [{ k: 'w', label: 'What do you want to do?', type: 'select', options: [['-', 'Take a percentage off'], ['+', 'Add a percentage on']], def: '-' }, { k: 'a', label: 'Cell with the price', hint: 'Like B2.', def: 'B2' }, { k: 'p', label: 'The percentage', hint: 'Just the number, like 10 for 10%.', def: '10' }], make: (v) => `=${v.a}*(1${v.w}${v.p || 0}%)` },
    { id: 'ROUND', name: 'Round a number', blurb: 'Tidy up long decimals.', fields: [{ k: 'a', label: 'Cell to round', hint: 'Like B2.', def: 'B2' }, { k: 'd', label: 'How many decimal places?', hint: '0 = whole number, 2 = like money.', def: '2' }], make: (v) => `=ROUND(${v.a},${v.d || 0})` },
    { id: 'IF', name: 'If this, then that', blurb: 'Show one answer or another depending on a test.', fields: [{ k: 'a', label: 'Which cell do you want to test?', hint: 'Like B2.', def: 'B2' }, { k: 'op', label: 'The test', type: 'select', options: [['>=', 'is at least (≥)'], ['>', 'is more than (>)'], ['<=', 'is at most (≤)'], ['<', 'is less than (<)'], ['=', 'is exactly equal to'], ['<>', 'is not equal to']], def: '>=' }, { k: 'n', label: 'Compare with', hint: 'A number or a cell.', def: '50' }, { k: 'yes', label: 'If the test is true, show', hint: 'Words are fine, e.g. Pass.', def: 'Pass' }, { k: 'no', label: 'If not, show', hint: 'Words are fine, e.g. Fail.', def: 'Fail' }], make: (v) => `=IF(${v.a}${v.op}${v.n},${q(v.yes)},${q(v.no)})` },
    { id: 'SUMIF', name: 'Add up only matching rows', blurb: 'Like SUM, but only for rows that match.', fields: [{ k: 'c', label: 'Cells to check', hint: 'The column with the categories, like A2:A20.', def: 'A2:A6' }, { k: 'm', label: 'What should they match?', hint: 'A word such as Apples.', def: 'Apples' }, { k: 's', label: 'Cells to add up', hint: 'Same size as the first group, like D2:D20.', def: 'D2:D6' }], make: (v) => `=SUMIF(${v.c},${q(v.m)},${v.s})` },
    { id: 'COUNTIF', name: 'Count only matching rows', blurb: 'How many rows match a rule?', fields: [{ k: 'c', label: 'Cells to check', hint: 'Like A2:A20.', def: 'B2:B6' }, { k: 'm', label: 'Rule', hint: 'A word (Apples) or a test (>5, <=10, <>0).', def: '>2' }], make: (v) => `=COUNTIF(${v.c},${q(v.m)})` },
    { id: 'VLOOKUP', name: 'Look something up in a table', blurb: 'Finds a row by name/code and returns another column.', fields: [{ k: 'f', label: 'What are you looking for?', hint: 'A cell (like F2) or a word.', def: 'Milk' }, { k: 't', label: 'Where is the table?', hint: 'The whole table, like A2:D20. What you look up must be in its first column.', def: 'A2:D6' }, { k: 'c', label: 'Which column do you want back?', hint: 'Count from the left of the table: 1, 2, 3…', def: '2' }], make: (v) => `=VLOOKUP(${/^[A-Za-z]{1,3}\d+$/.test(v.f) ? v.f : q(v.f)},${v.t},${v.c},FALSE)` },
    { id: 'JOIN', name: 'Join text together', blurb: 'Like first name + last name.', fields: [{ k: 'a', label: 'First cell', hint: 'Like A2.', def: 'A2' }, { k: 'sep', label: 'What goes in between?', hint: 'A space is most common. Leave blank for nothing.', def: ' ' }, { k: 'b', label: 'Second cell', hint: 'Like B2.', def: 'B2' }], make: (v) => `=${v.a}&${q(v.sep || '')}&${v.b}` },
    { id: 'SAFE', name: 'Hide errors', blurb: 'Replace an error with something tidy.', fields: [{ k: 'f', label: 'Your formula (without the =)', hint: 'Like B2/C2.', def: 'B2/C2' }, { k: 'o', label: 'Show this instead of an error', hint: 'Leave blank to show nothing.', def: '' }], make: (v) => `=IFERROR(${v.f.replace(/^=/, '')},${q(v.o || '')})` },
  ];
  function q(s) { s = String(s == null ? '' : s); return /^-?\d+(\.\d+)?$/.test(s.trim()) && s.trim() !== '' ? s.trim() : '"' + s.replace(/"/g, '""') + '"'; }


  /* ---------- Lessons (full set) ---------- */
  /* ---------- Lessons ---------- */
  const LESSONS = [
    { id: 'screen', title: 'Meet the Excel screen', mins: 3, intro: 'Excel looks busy, but you only need to know six things.', steps: ['<b>Cell</b> – one box. Click it to select it. Its name (like <b>B3</b>) is its column letter + row number.', '<b>Columns</b> run up and down and have letters (A, B, C…). <b>Rows</b> run across and have numbers (1, 2, 3…).', '<b>The ribbon</b> is the strip of buttons at the top. Its tabs (Home, Insert, Data…) group the buttons.', '<b>The formula bar</b> sits above the grid. It shows exactly what is inside the selected cell.', '<b>Sheet tabs</b> at the bottom let you have several pages in one file. Click <b>+</b> to add one.', '<b>The Name Box</b> (top left) shows which cell you are in. Type a cell name there and press Enter to jump to it.'], practice: null },
    { id: 'type', title: 'Typing and moving around', mins: 3, intro: 'The basics: putting things into cells.', steps: ['Click a cell and just start typing. No need to double-click.', 'Press <b>Enter</b> to finish and move down. Press <b>Tab</b> to finish and move right.', 'Press <b>Esc</b> to cancel what you are typing.', 'To change a cell, click it and start typing (this replaces it), or press <b>F2</b> to edit what is already there.', 'To delete, select cells and press <b>Delete</b>.', 'Made a mistake? Press <b>Ctrl + Z</b> (Cmd + Z on Mac). You can undo many steps.'], practice: 'Try it in the practice sheet: click a cell, type your name and press Enter.' },
    { id: 'first', title: 'Your first formula', mins: 4, intro: 'A formula is a cell that does maths for you. It always starts with <b>=</b>.', steps: ['Click an empty cell and type <b>=2+3</b>, then press Enter. You will see <b>5</b>.', 'Click that cell again and look at the formula bar: it still says =2+3. The cell shows the answer; the bar shows the recipe.', '<b>+</b> add, <b>−</b> subtract, <b>*</b> multiply, <b>/</b> divide.', 'Better: use cell names. Type 10 in A1 and 5 in A2. In A3 type <b>=A1+A2</b>.', 'Change A1 to 20. A3 updates by itself. That is the magic of Excel.'], practice: 'Try =A1+A2 in the practice sheet.', example: '=B2*C2' },
    { id: 'sum', title: 'Adding up with SUM', mins: 3, intro: 'Adding lots of numbers with + is slow. SUM does it in one go.', steps: ['Click the cell where you want the total.', 'Type <b>=SUM(</b>.', 'Drag your mouse over the numbers. Excel writes the range for you, like <b>B2:B6</b> (the colon means "through").', 'Type <b>)</b> and press Enter.', 'Even faster: click below the numbers and press <b>Alt + =</b>. Excel guesses the range.'], practice: 'Try =SUM(D2:D6) in the practice sheet.', example: '=SUM(D2:D6)' },
    { id: 'avg', title: 'Average, biggest, smallest, count', mins: 3, intro: 'Four more one-word helpers, all used exactly like SUM.', steps: ['<b>=AVERAGE(B2:B6)</b> – the typical number.', '<b>=MAX(B2:B6)</b> – the biggest.', '<b>=MIN(B2:B6)</b> – the smallest.', '<b>=COUNT(B2:B6)</b> – how many numbers.', 'All follow the same pattern: <b>=NAME( cells )</b>.'], practice: 'Try each one on the prices in column B.', example: '=AVERAGE(B2:B6)' },
    { id: 'look', title: 'Make it look nice', mins: 4, intro: 'Good looks make a sheet easy to read.', steps: ['Select the heading row, press <b>Ctrl + B</b> for bold.', 'Double-click the line between two column letters to fit the column to its contents.', 'Select money cells and click the <b>$</b> button on the Home tab.', 'Use the <b>paint bucket</b> to colour cells and the <b>A</b> button to colour text.', 'Use <b>borders</b> (the square icon) to draw lines around a table.', 'Seeing <b>####</b>? The column is too narrow. Widen it.'], practice: null },
    { id: 'sort', title: 'Sort and filter', mins: 3, intro: 'Put things in order, or hide what you do not need.', steps: ['Click any cell in your table.', '<b>Sort:</b> Data tab → A→Z (smallest first) or Z→A.', '<b>Filter:</b> press <b>Ctrl + Shift + L</b>. Arrows appear on your headings.', 'Click an arrow, tick what to show, press OK.', 'Press Ctrl + Shift + L again to turn filtering off.', 'Filtering only <i>hides</i> rows. It never deletes them.'], practice: null },
    { id: 'copy', title: 'Copy a formula down', mins: 4, intro: 'Write a formula once, then reuse it on every row.', steps: ['Write the formula in the first row, e.g. <b>=B2*C2</b>.', 'Click it. Find the small green square in its bottom-right corner (the <b>fill handle</b>).', 'Double-click the square. Excel copies the formula down as far as your data goes.', 'Look at the copies: row 3 says =B3*C3, row 4 says =B4*C4. Excel changed the row numbers for you.', 'Need a cell to stay put (like a tax rate in F1)? Write <b>$F$1</b>. The $ signs lock it. Press <b>F4</b> to add them quickly.'], practice: 'In the practice sheet, type =B2*C2 in D2, then fix it by hand in D3…', example: '=B2*C2' },
    { id: 'if', title: 'Letting Excel decide with IF', mins: 4, intro: 'IF shows one thing when a test is true and another when it is not.', steps: ['The pattern: <b>=IF( test , if true , if false )</b>.', 'Example: <b>=IF(B2>=2,"Pricey","Cheap")</b>.', 'Words go in <b>"double quotes"</b>. Numbers do not.', 'Tests use <b>&gt;</b> more than, <b>&lt;</b> less than, <b>=</b> equal, <b>&lt;&gt;</b> not equal, <b>&gt;=</b> at least.', 'Use the Formula Builder tab and pick "If this, then that" to fill it in without typing.'], practice: 'Try the example in the practice sheet.', example: '=IF(B2>=2,"Pricey","Cheap")' },
    { id: 'chart', title: 'Make a chart in 3 clicks', mins: 3, intro: 'Charts turn numbers into pictures.', steps: ['Select your data including the headings.', 'Click <b>Insert → Recommended Charts</b>.', 'Pick one that looks good and press OK.', 'Click the chart title to rename it.', 'Bar charts compare things, line charts show change over time, pie charts show parts of a whole.'], practice: null },
    { id: 'save', title: 'Save, print and share', mins: 3, intro: 'Do not lose your work!', steps: ['<b>Ctrl + S</b> saves (Cmd + S on Mac). Do it every few minutes.', 'The first time, choose a place and name.', 'To print, press <b>Ctrl + P</b> and check the preview.', 'To make a PDF, pick <b>Save as PDF</b> / <b>Print to PDF</b> as the printer.', 'To email it, File → Share (or attach the saved file).', 'If Excel crashes, reopen it: it usually offers to recover your work.'], practice: null },
  ];


  /* ---------- Practice sheet starter ---------- */
  const SAMPLE = { A1: 'Item', B1: 'Price', C1: 'Qty', D1: 'Total', A2: 'Apples', B2: '1.5', C2: '4', D2: '=B2*C2', A3: 'Bread', B3: '2.25', C3: '2', D3: '=B3*C3', A4: 'Milk', B4: '1.2', C4: '3', D4: '=B4*C4', A5: 'Eggs', B5: '3.4', C5: '1', D5: '=B5*C5', A6: 'Coffee', B6: '7.9', C6: '2', D6: '=B6*C6', A8: 'Grand total', D8: '=SUM(D2:D6)' };

  const CHALLENGES = [
    { text: 'Type your name into cell F1.', check: (s) => /\S/.test(s.getRaw('F1')) },
    { text: 'In D7, add up the Qty column (C2:C6) with SUM.', check: (s) => /^=\s*SUM\(/i.test(s.getRaw('D7')) && s.value('D7') === 12 },
    { text: 'In E2, show "Pricey" if the price in B2 is 2 or more, otherwise "Cheap", using IF.', check: (s) => /^=\s*IF\(/i.test(s.getRaw('E2')) && /pricey|cheap/i.test(s.getRaw('E2')) },
    { text: 'In E8, find the average price with AVERAGE(B2:B6).', check: (s) => { try { return Math.abs(Number(s.value('E8')) - 3.25) < 1e-9; } catch (e) { return false; } } },
  ];


  return { BUILDER, LESSONS, SAMPLE, CHALLENGES };
})();
